### ISSUE TITLE
LaTeX Formulas Not Rendering

### ISSUE THREAD

**Issue by mbabatunde** [peter-can-write/david-silver-rl-notes#1]
Hi @goldsborough,

Great notes on Reinforcement Learning! However, I came across an issue with your markdown notes. 

Github has no native way of supporting LaTeX formulas in their flavored markdown, so a workaround is needed to properly render the formulas.

In order to get around this problem, one would need to make use a site like [CodeCogs](https://www.codecogs.com/latex/eqneditor.php) in order to convert the said formula into an image. One could then place the image in the same directory where your markdown files live and use in-line image style like ``` ![alt text](Link to image)``` to properly display the formula.

Example:

<img width="957" alt="screen shot 2018-02-26 at 5 23 14 pm" src="https://user-images.githubusercontent.com/21072448/36699185-f36db840-1b19-11e8-9c2c-21900d221e64.png">

**Comment by goldsborough** [comment]
Hi, thanks. Yes, I'm aware of this. I read/write my notes in Atom with the Markdown Preview plugin, which can render LaTex. I think there are too many equations to turn them all into images. You can use a markdown reader that supports rendering LaTex. pandoc also has support for rendering LaTex I believe.
